svn:5100 1) set DISPLAY only if empty 2) new version of ZVView (binary for Window, Linux, MacOSX)

diff --git a/util/c4zvd/c4zvv b/util/c4zvd/c4zvv
--- a/util/c4zvd/c4zvv
+++ b/util/c4zvd/c4zvv
@@ -19,5 +19,14 @@ cat c4.zvd >$file-$MT.zvd
 cat end.zvd >>$file-$MT.zvd
 rm c4.zvd end.zvd tmp.dat 2>/dev/null         
 $EMPIREDIR/util/c4zvd/zvview.exe $file-$MT.zvd ps01.tit/c
+    errCode=$?
+    #echo -n "___Pause. Press any key..."; read yes
+    #if [ $errCode -ne 0 ]; then
+    if [ $errCode -ne 0 -a $errCode -ne 1 ]; then
+        set +x
+        echo    "___ERROR running ZVView: errCode=$errCode"
+        echo    "___DISPLAY=$DISPLAY"
+        echo -n "___Pause. Press any key..."; read yes
+    fi
 
 
diff --git a/util/c4zvd/pntzvdl b/util/c4zvd/pntzvdl
--- a/util/c4zvd/pntzvdl
+++ b/util/c4zvd/pntzvdl
@@ -22,10 +22,28 @@ cat pnt.zvd >>$3
 cat cur.zvd >>$3
 if [ "$4" = "" ]; then
    $EMPIREDIR/util/c4zvd/zvview.exe $3 ps01.tit/c
+    errCode=$?
+    #echo -n "___Pause. Press any key..."; read yes
+    #if [ $errCode -ne 0 ]; then
+    if [ $errCode -ne 0 -a $errCode -ne 1 ]; then
+        set +x
+        echo    "___ERROR running ZVView: errCode=$errCode"
+        echo    "___DISPLAY=$DISPLAY"
+        echo -n "___Pause. Press any key..."; read yes
+    fi
    exit
 fi
 #next line makes use of the ddx.tit file with plot settings
 $EMPIREDIR/util/c4zvd/zvview.exe -p:tmp $3 ddx.tit </dev/null
+    errCode=$?
+    #echo -n "___Pause. Press any key..."; read yes
+    #if [ $errCode -ne 0 ]; then
+    if [ $errCode -ne 0 -a $errCode -ne 1 ]; then
+        set +x
+        echo    "___ERROR running ZVView: errCode=$errCode"
+        echo    "___DISPLAY=$DISPLAY"
+        echo -n "___Pause. Press any key..."; read yes
+    fi
 rm tmp.dat 2>/dev/null
 rm pnt.zvd 2>/dev/null
 rm cur.zvd 2>/dev/null
