svn:4182 Scripts were modified to detect crashes and exit gracefully. The existence of corresponding input files is also checked.

diff --git a/scripts/addresonances b/scripts/addresonances
--- a/scripts/addresonances
+++ b/scripts/addresonances
@@ -17,6 +17,18 @@ else
     ln -sf $file-res.endf ENDRES.DAT
 fi
 
+# Checking if input file available
+if [ ! -f $file-e.endf ]; then
+echo ' '
+echo 'ERROR: Input file '$file'-e.endf is missing'
+echo 'Formatting (EMPEND) should be run first ! '
+echo ' '
+read -p " Press any key to exit or <CTRL>-C to abort ..."
+echo ' '
+exit 1
+fi
+
+
 ln -sf $EMPIREDIR/util/endres/ENDRES.INP ENDRES.INP
 
 rm empire.end endf.dat 2>/dev/null
diff --git a/scripts/format b/scripts/format
--- a/scripts/format
+++ b/scripts/format
@@ -26,11 +26,12 @@ fi
 if [ ! -f $file.out ]; then
 echo ' '
 echo ' '
-echo 'ERROR: EMPIRE output is not available (Run Empire or check the long listing)'
+echo 'ERROR: EMPIRE output file '$file'.out is missing'
+echo '     execute EMPIRE before formatting  !            '
 echo ' '
-echo -n 'Press any key to continue ..'
-read anykey
-exit
+read -p " Press  <Enter> key to exit or <CTRL>-C to abort ..."
+echo ' '
+exit 1
 fi
 
 # Deleting previous file if exist
@@ -50,19 +51,17 @@ $2
 LABLABLABL EVAL-`date "+%b%y"` AUTHORAUTHORAUTHORAUTHORAUTHORAUT
 EOF
 $EMPIREDIR/util/empend/empend <EMPEND.INP
+rc=$?
 mv empend.log $file-log.empend
 rm EMPEND.INP empmf1.tmp
-
-# Checking if EMPEND run sucessfully 
-if [ ! -f $file-e.endf ]; then
-echo ' '
-echo ' '
-echo 'ERROR: ENDF formatting failed, rerun format or Empire'
-echo '       Pls notify Dr. A.Trkov at a.trkov@iaea.org    '
-echo ' '
-echo -n 'Press any key to continue ..'
-read anykey
-exit
+if [[ $rc != 0 ]] ; then
+   echo ' '
+   echo ' EMPEND crashed, check log file '$file'-log.empend for diagnostics!'
+   echo ' Please notify Dr.A.Trkov at a.trkov@iaea.org                      '
+   echo ' '
+   read -p " Press <Enter> key to exit or <CTRL>-C to abort ..."
+   echo ' '
+   exit 3
 fi
 
 # RUN ENDRES (IF RESONANCE FILE IS PRESENT)
@@ -94,6 +93,15 @@ $file.endf
 DONE
 EOF
 $EMPIREDIR/util/stanef/stanef <INPUT
+rc=$?
+if [[ $rc != 0 ]] ; then
+   echo ' '
+   echo ' STANEF crashed, please notify Dr.A.Trkov at a.trkov@iaea.org '
+   echo ' '
+   read -p " Press any key to exit or <CTRL>-C to abort ..."
+   echo ' '
+   exit $rc
+fi
 
 #echo $file.endf was produced by STANEF
 # remove left-over files
diff --git a/scripts/multiE b/scripts/multiE
--- a/scripts/multiE
+++ b/scripts/multiE
@@ -7,25 +7,78 @@ echo par1=$0
 echo par2=$1
 echo par3=$2
 echo par3=$3
-echo EMPIREDIR=$EMPIREDIR
-echo PWD=$PWD
+#echo EMPIREDIR=$EMPIREDIR
+#echo PWD=$PWD
 
 file=$1
 MAT=$2
 actions=$3
 dd=$EMPIREDIR/scripts
 
+read -p " Press <Enter> key to continue ..."
+ 
     ls0=${#actions}
     i=0
     while [ $i -lt $ls0 ] ; do
 	ch=${actions:i:1}
 	#echo i=$i ch=[$ch]
 	if [ "$ch" = "1" ] ; then
-	    if [ "$i" = "0" ] ; then python $dd/runE $file $MAT; fi
-	    if [ "$i" = "2" ] ; then $dd/format $file $MAT ; fi
-	    if [ "$i" = "4" ] ; then $dd/verify $file $MAT ; fi
-	    if [ "$i" = "6" ] ; then $dd/process $file $MAT ; fi
-	    if [ "$i" = "8" ] ; then $dd/addresonances $file $MAT ; fi
+	    if [ "$i" = "0" ] ; then 
+              python $dd/runE $file $MAT; 
+              rc=$?
+              if [[ $rc == 1 ]] ; then
+                echo ' '
+                echo ' EMPIRE input file '$file'.inp not found !'
+                echo ' '
+                read -p " Press <Enter> key to exit ..."
+                echo ' '
+                exit 1
+              fi
+              if [[ $rc == 2 ]] ; then
+                echo ' '
+                echo ' Check the long output '$file'.lst for diagnostics !'
+                echo ' '
+                read -p " Press <Enter> key to exit ..."
+                echo ' '
+                exit 1
+              fi
+              if [[ $rc != 0 ]] ; then
+                echo ' '
+                echo ' Indetermined error. Check the long output '$file'.lst for diagnostics !'
+                echo ' '
+                read -p " Press <Enter> key to exit ..."
+                echo ' '
+                exit 1
+              fi
+          fi
+	    if [ "$i" = "2" ] ; then 
+             $dd/format $file $MAT ; 
+             rc=$?
+             if [[ $rc != 0 ]] ; then
+               exit 1
+             fi
+          fi
+	    if [ "$i" = "4" ] ; then 
+             $dd/verify $file $MAT ; 
+             rc=$?
+             if [[ $rc != 0 ]] ; then
+               exit 1
+             fi
+          fi
+	    if [ "$i" = "6" ] ; then 
+             $dd/process $file $MAT ; 
+             rc=$?
+             if [[ $rc != 0 ]] ; then
+               exit 1
+             fi
+          fi
+	    if [ "$i" = "8" ] ; then 
+             $dd/addresonances $file $MAT ;
+             rc=$?
+             if [[ $rc != 0 ]] ; then
+               exit 1
+             fi
+          fi
 	fi
 	i=$(($i+1))
     done
diff --git a/scripts/process b/scripts/process
--- a/scripts/process
+++ b/scripts/process
@@ -19,6 +19,17 @@ echo -n 'Choose one of the above (without .endf extention!): '
 read file
 fi                          
 
+# Checking if input file available
+if [ ! -f $file.endf ]; then
+echo ' '
+echo 'ERROR: Input file '$file'.endf is missing               '
+echo 'EMPIRE and Formatting (EMPEND) should be executed first!'
+echo ' '
+read -p " Press any key to exit or <CTRL>-C to abort ..."
+echo ' '
+exit 1
+fi
+
 # RUN LINEAR
 
 rm LINEAR.INP 2>/dev/null
@@ -59,7 +70,7 @@ mv ENDFB.OUT $work/$file-mub.endf
 # Running LEGEND to convert angular distributions into tabular form
 # cp $work/$file-mub.endf $work/$file-l.endf
 
-rm $file-l.endf 2>/dev/null
+rm $file-l.endf LEGEND.INP ENDF.IN 2>/dev/null
 ln -sf $work/$file-mub.endf ENDF.IN
 ln -sf $EMPIREDIR/util/legend/LEGEND.INP LEGEND.INP
 
@@ -70,7 +81,7 @@ mv LEGEND.LST $work/$file-log.legend
 
 # RUN SIXTAB TO PREPARE FILE 6 FOR PLOTTING
 
-rm $file-s.endf 2>/dev/null
+rm $file-s.endf ENDF.IN SIXTAB.INP 2>/dev/null
 ln -sf $work/$file-l.endf ENDF.IN
 ln -sf $EMPIREDIR/util/sixtab/SIXTAB.INP SIXTAB.INP
 
diff --git a/scripts/verify b/scripts/verify
--- a/scripts/verify
+++ b/scripts/verify
@@ -19,6 +19,16 @@ echo -n 'Choose one of the above (without .endf extention!): '
 read file
 fi                          
 
+# Checking if input file available
+if [ ! -f $file.endf ]; then
+echo ' '
+echo ' ERROR: Input file '$file'.endf is missing               '
+echo ' EMPIRE and Formatting (EMPEND) should be executed first!'
+echo ' '
+read -p " Press any key to exit or <CTRL>-C to abort ..."
+echo ' '
+exit 1
+fi
 
 # RUN CHECKR
 
