svn:5097 1) set DISPLAY only if empty 2) check correctness of running ZVView

diff --git a/scripts/grepawk b/scripts/grepawk
--- a/scripts/grepawk
+++ b/scripts/grepawk
@@ -17,6 +17,16 @@ echo '//'>>$1.res
 XWIN=`uname`
 if [ "$XWIN" = "Darwin" ] 
 then
-  export DISPLAY=:0
+   if [ -z $DISPLAY ]; then export DISPLAY=:0 ; fi
 fi
+
 $EMPIREDIR/util/c4zvd/zvview.exe $1.res/u
+    errCode=$?
+    #echo -n "___Pause. Press any key..."; read yes
+    #if [ $errCode -ne 0 ]; then
+    if [ $errCode -ne 0 -a $errCode -ne 1 ]; then
+        set +x
+        echo    "___ERROR running ZVView: errCode=$errCode"
+        echo    "___DISPLAY=$DISPLAY"
+        echo -n "___Pause. Press any key..."; read yes
+    fi
