svn:2168 Update on kalman script. Instead of looking for a .c4 file, the script now uses a file ending with -kal.c4. If this file is not present, it copies the existing .c4 file into -kal.c4 and then uses it. This was done because usually the complete c4 file has to be edited before running kalman, making it useful to have two separate c4 files.

diff --git a/scripts/kalman b/scripts/kalman
--- a/scripts/kalman
+++ b/scripts/kalman
@@ -43,9 +43,14 @@ if [ ! -s $file-mat.sen ]; then
    echo "SENSITIVITY FILE NOT FOUND ($file-mat.sen)"
    exit 3
 fi
-if [ ! -s $file.c4 ]; then
-   echo "C4 FILE NOT FOUND ($file.c4)"
-   exit 4
+if [ ! -s $file-kal.c4 ]; then
+   echo "$file-kal.c4 NOT FOUND. USING $file.c4 INSTEAD."
+   if [ ! -s $file.c4 ]; then
+     echo "C4 FILE NOT FOUND ($file.c4)"
+     exit 4
+   else
+     cp $file.c4 $file-kal.c4
+   fi
 fi
 
 
@@ -60,7 +65,7 @@ rm $file-{c4,par,*-err}.kal 2>/dev/null
 
 # parse .c4 file for only reactions (MT #s) of interest:
 for j in "  1" "  2" "  3" "  4" " 16" " 17" " 18" "102" "103" "107"; do
-    grep "^.\{12,19\}  3 $j " $file.c4 >>$file-c4.kal
+    grep "^.\{12,19\}  3 $j " $file-kal.c4 >>$file-c4.kal
 done
 
 for k in $MT; do
