svn:5409 Cosmetic.

diff --git a/scripts/multiE b/scripts/multiE
--- a/scripts/multiE
+++ b/scripts/multiE
@@ -27,100 +27,98 @@ MAT=$2
 #echo $actions ' and ' ${#actions} 
 dd=$EMPIREDIR/scripts
 
-          if [ "$3" = "1" ]
-            then
-              python $dd/runE $file $MAT; 
-              rc=$?
-              if [ $rc = 1 ]  
-              then
-                echo ' '
-                echo ' EMPIRE input file '$file'.inp not found !'
-                echo ' '
-                echo 'Press <Enter> to exit'
-                read yes
-                echo ' '
-                exit 1
-              fi
-              if [ $rc = 2 ] 
-              then
-                echo ' '
-                echo ' Check the long output '$file'.lst for diagnostics !'
-                echo ' '
-                echo 'Press <Enter> to exit'
-                read yes
-                echo ' '
-                exit 1
-              fi
-              if [ $rc != 0 ] 
-              then
-                echo ' '
-                echo ' Indetermined error. Check the long output '$file'.lst for diagnostics !'
-                echo ' '
-                echo 'Press <Enter> to exit'
-                read yes
-                echo ' '
-                exit 1
-              fi
-          fi
-	  
-          # remove empty files
-          find . -empty -type f -delete
-
-          if [ "$4" = "1" ]
-            then
-             $dd/format $file $MAT ; 
-             rc=$?
-             if [ $rc != 0 ]  
-             then
-               echo ' '
-               echo ' Error while formatting !'
-               echo ' '
-               echo 'Press <Enter> to exit'
-               read yes
-               exit 1
-             fi
-          fi
-          if [ "$5" = "1" ]
-            then
-             $dd/verify $file $MAT ; 
-             rc=$?
-             if [ $rc != 0 ]  
-             then
-               echo ' '
-               echo ' Error while verifying !'
-               echo ' '
-               echo 'Press <Enter> to exit'
-               read yes
-               exit 1
-             fi
-          fi
-          if [ "$6" = "1" ]
-            then
-             $dd/process $file $MAT ; 
-             rc=$?
-             if [ $rc != 0 ]  
-             then
-               echo ' '
-               echo ' Error while processing !'
-               echo ' '
-               echo 'Press <Enter> to exit'
-               read yes
-               exit 1
-             fi
-          fi
-          if [ "$7" = "1" ]
-            then
-             $dd/addresonances $file $MAT ;
-             rc=$?
-             if [ $rc != 0 ]  
-             then
-               echo ' '
-               echo ' Error while adding resonances !'
-               echo ' '
-               echo 'Press <Enter> to exit'
-               read yes
-               exit 1
-             fi
-          fi
+if [ "$3" = "1" ]
+  then
+    python $dd/runE $file $MAT; 
+    rc=$?
+    if [ $rc = 1 ]  
+    then
+      echo ' '
+      echo ' EMPIRE input file '$file'.inp not found !'
+      echo ' '
+      echo 'Press <Enter> to exit'
+      read yes
+      echo ' '
+      exit 1
+    fi
+    if [ $rc = 2 ] 
+    then
+      echo ' '
+      echo ' Check the long output '$file'.lst for diagnostics !'
+      echo ' '
+      echo 'Press <Enter> to exit'
+      read yes
+      echo ' '
+      exit 1
+    fi
+    if [ $rc != 0 ] 
+    then
+      echo ' '
+      echo ' Indetermined error. Check the long output '$file'.lst for diagnostics !'
+      echo ' '
+      echo 'Press <Enter> to exit'
+      read yes
+      echo ' '
+      exit 1
+    fi
+fi
+# remove empty files
+find . -empty -type f -delete
+if [ "$4" = "1" ]
+  then
+   $dd/format $file $MAT ; 
+   rc=$?
+   if [ $rc != 0 ]  
+   then
+     echo ' '
+     echo ' Error while formatting !'
+     echo ' '
+     echo 'Press <Enter> to exit'
+     read yes
+     exit 1
+   fi
+fi
+if [ "$5" = "1" ]
+  then
+   $dd/verify $file $MAT ; 
+   rc=$?
+   if [ $rc != 0 ]  
+   then
+     echo ' '
+     echo ' Error while verifying !'
+     echo ' '
+     echo 'Press <Enter> to exit'
+     read yes
+     exit 1
+   fi
+fi
+if [ "$6" = "1" ]
+  then
+   $dd/process $file $MAT ; 
+   rc=$?
+   if [ $rc != 0 ]  
+   then
+     echo ' '
+     echo ' Error while processing !'
+     echo ' '
+     echo 'Press <Enter> to exit'
+     read yes
+     exit 1
+   fi
+fi
+if [ "$7" = "1" ]
+  then
+   $dd/addresonances $file $MAT ;
+   rc=$?
+   if [ $rc != 0 ]  
+   then
+     echo ' '
+     echo ' Error while adding resonances !'
+     echo ' '
+     echo 'Press <Enter> to exit'
+     read yes
+     exit 1
+   fi
+fi
 
 exit
