svn:3934 Created option 'replaceaux' in runbench script to replace existing *.lev and *-lev.col files by default-generated ones.

diff --git a/scripts/runbench b/scripts/runbench
--- a/scripts/runbench
+++ b/scripts/runbench
@@ -178,6 +178,47 @@ elif [ "$option" = "replace" ] ; then
      done
    done
 
+elif [ "$option" = "replaceaux" ] ; then
+#  regenerates auxiliary *.lev *-lev.col files by running benchmarks without them and keeping them afterwards.
+   echo 'Deleting auxiliary *.lev *-lev.col files'
+   rm *.lev *-lev.col
+   echo
+   echo "Running benchmarks..."
+   echo
+   mkdir TeMpOrArYdIr
+   cp u238-HFB-num-fis-tun-inp.fis TeMpOrArYdIr/
+   cp *.inp *ref* TeMpOrArYdIr/ >& /dev/null
+   error=0
+   for file in $filelist
+   do
+     echo "" 1>&2
+     echo ".......Running benchmark on [$file]......." 1>&2
+     $EMPIREDIR/scripts/runE $file
+     grep -q 'CALCULATIONS COMPLETED SUCCESSFULLY' $file.lst
+     if [ "$?" = 1 ] ; then
+       error=1
+       echo "#######Calculations Failed#######" 1>&2
+     else
+       echo ".......Calculations Completed Successfully......." 1>&2
+     fi
+     cp $file.inp $file-ref.* TeMpOrArYdIr/ >& /dev/null
+     for suffix in $suffix_list
+     do
+       cp $file.$suffix TeMpOrArYdIr/
+     done
+   done
+   cp *lev *-lev.col TeMpOrArYdIr/
+   rm * >& /dev/null
+   rm -r *-tl  >& /dev/null
+   mv TeMpOrArYdIr/* ./
+   rm -r TeMpOrArYdIr >& /dev/null
+
+   if [ "$error" = 1 ] ; then
+     echo "ERROR!! At least one of the benchmarks failed to run successfully!"
+     exit 1
+   fi
+
+
 else
    echo
    echo "Current options are:"
@@ -186,6 +227,7 @@ else
    echo " 'runbench clean' to remove temporary files and keep only original ones"
    echo " 'runbench diff' to compare benchmarks output with existing reference files (using diff command)"
    echo " 'runbench kompare' to compare benchmarks output with existing reference files (using kompare)"
-   echo " 'runbench replace' to replace existing reference files with benchmarks outputs (using perl-based 'rename' command)"
+   echo " 'runbench replace' to replace existing reference files with benchmarks outputs"
+   echo " 'runbench replaceaux' to regenerate and replace existing auxiliary files *.lev and *-lev.col (by running Empire)"
    echo
 fi   
