svn:5099 1) set DISPLAY only if $DISPLAY is empty (can be set outside) 2) check system Error when running ZVView (for debugging on MacOSX)

diff --git a/scripts/showzvd b/scripts/showzvd
--- a/scripts/showzvd
+++ b/scripts/showzvd
@@ -8,13 +8,22 @@ fi
 XWIN=`uname`
 if [ "$XWIN" = "Darwin" ] 
 then
-export DISPLAY=:0
+   if [ -z $DISPLAY ]; then export DISPLAY=:0 ; fi
 fi
 
 ln -s $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit        
 for file in $*
 do
 $EMPIREDIR/util/c4zvd/zvview.exe -p:$file $file ps01.tit/c
+    errCode=$?
+    #echo -n "___Pause. Press any key..."; read yes
+    #if [ $errCode -ne 0 ]; then
+    if [ $errCode -ne 0 -a $errCode -ne 1 ]; then
+        set +x
+        echo    "___ERROR running ZVView: errCode=$errCode"
+        echo    "___DISPLAY=$DISPLAY"
+        echo -n "___Pause. Press any key..."; read yes
+    fi
 if [ -f zv00.ps ]; then
    mv zv00.ps $file.ps
 fi
diff --git a/scripts/zvcomb b/scripts/zvcomb
--- a/scripts/zvcomb
+++ b/scripts/zvcomb
@@ -7,9 +7,8 @@ if [ -z $EMPIREDIR ]; then
 fi
 
 XWIN=`uname`
-if [ "$XWIN" = "Darwin" ] 
-then
-export DISPLAY=:0
+if [ "$XWIN" = "Darwin" ]; then
+   if [ -z $DISPLAY ]; then export DISPLAY=:0 ; fi
 fi
 
 set -x
@@ -28,7 +27,18 @@ if [ ! -f ps01.tit ]; then
    cp $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit
 !  ln -s $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit
 fi
+
 $EMPIREDIR/util/c4zvd/zvview.exe ps01.tit/c $file
+    errCode=$?
+    #echo -n "___Pause. Press any key..."; read yes
+    #if [ $errCode -ne 0 ]; then
+    if [ $errCode -ne 0 -a $errCode -ne 1 ]; then
+        set +x
+        echo    "___ERROR running ZVView: errCode=$errCode"
+        echo    "___DISPLAY=$DISPLAY"
+        echo -n "___Pause. Press any key..."; read yes
+    fi
+
 !rm ps01.tit
 if [ -f zv00.ps ]; then
    mv zv00.ps $1-mrg.ps
diff --git a/scripts/zvd b/scripts/zvd
--- a/scripts/zvd
+++ b/scripts/zvd
@@ -1,31 +1,53 @@
 #! /bin/sh -
-#script to  display exp. and calculated data with ZVView
+#script to  display exp. and calculated data with ZVView by V. Zerkin
 
 XWIN=`uname`
 if [ "$XWIN" = "Darwin" ] 
-    then
-    export DISPLAY=:0
+then
+   if [ -z $DISPLAY ]; then export DISPLAY=:0 ; fi
 fi
+
 file=$1
 MT=$2
 work=`pwd`
 if [ "$1" = "" ]
-    then
-    echo 'Inputs ready to run'
-    echo ' '
-    ls *endf  
-    echo ' '
-    echo -n 'Choose one of the above (without .endf extention!): '
-    read file
+   then
+echo 'Inputs ready to run'
+echo ' '
+ls *endf  
+echo ' '
+echo -n 'Choose one of the above (without .endf extention!): '
+read file
 fi                          
 if [ "$2" = "" ]
-    then
-    echo -n 'Input MT number to be plotted: '
-    read MT
+   then
+echo -n 'Input MT number to be plotted: '
+read MT
 fi                          
 
+# FIRST RECONSTRUCT (N,N), (N,P), AND (N,A) REACTIONS WITH FIXUP
+
 if [ ! -f $file-s.endf ]; then
-    $EMPIREDIR/scripts/process $file 
+   #  FIXUP input expects file named OUTPUT.ENDF:   
+   ln -sf $work/$file.endf OUTPUT.ENDF
+   ln -sf $EMPIREDIR/util/fixup/FIXUP.INP FIXUP.INP
+    
+   $EMPIREDIR/util/fixup/fixup
+   rm OUTPUT.ENDF FIXUP.INP
+   mv FIXUP.ENDF $work/$file-f.endf
+
+   # RUN SIXTAB TO PREPARE FILE 6 FOR PLOTTING
+
+   ln -sf $work/$file-f.endf ENDF.IN
+   ln -sf $EMPIREDIR/util/sixtab/SIXTAB.INP SIXTAB.INP
+
+   $EMPIREDIR/util/sixtab/sixtab
+   rm ENDF.IN SIXTAB.INP
+   mv ENDF.OUT $work/$file-s.endf
+   if  [ -f $file-s.endf ]; then
+      rm $file-f.endf 2>/dev/null
+   fi   
+
 fi
 
 # RUN ZVD
@@ -51,6 +73,16 @@ cat c4.zvd >$file-$MT.zvd
 cat end.zvd >>$file-$MT.zvd
 ln -sf $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit
 $c4zvd_dir/zvview.exe -p:$file-$MT $file-$MT.zvd ps01.tit/c
+    errCode=$?
+    #echo -n "___Pause. Press any key..."; read yes
+    #if [ $errCode -ne 0 ]; then
+    if [ $errCode -ne 0 -a $errCode -ne 1 ]; then
+        set +x
+        echo    "___ERROR running ZVView: errCode=$errCode"
+        echo    "___DISPLAY=$DISPLAY"
+        echo -n "___Pause. Press any key..."; read yes
+    fi
+
 rm ps01.tit 2>/dev/null
 
 if [ -f zv00.ps ]; then
diff --git a/scripts/zvv b/scripts/zvv
--- a/scripts/zvv
+++ b/scripts/zvv
@@ -8,7 +8,7 @@ fi
 XWIN=`uname`
 if [ "$XWIN" = "Darwin" ] 
 then
-export DISPLAY=:0
+   if [ -z $DISPLAY ]; then export DISPLAY=:0 ; fi
 fi
 
 set -x
@@ -22,5 +22,14 @@ if [ ! -f ps01.tit ]; then
    cp $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit
 fi
 $EMPIREDIR/util/c4zvd/zvview.exe -p:$file $list ps01.tit/c
+    errCode=$?
+    #echo -n "___Pause. Press any key..."; read yes
+    #if [ $errCode -ne 0 ]; then
+    if [ $errCode -ne 0 -a $errCode -ne 1 ]; then
+        set +x
+        echo    "___ERROR running ZVView: errCode=$errCode"
+        echo    "___DISPLAY=$DISPLAY"
+        echo -n "___Pause. Press any key..."; read yes
+    fi
 #rm ps01.tit
 exit
diff --git a/scripts/zvvsenmat b/scripts/zvvsenmat
--- a/scripts/zvvsenmat
+++ b/scripts/zvvsenmat
@@ -45,10 +45,19 @@ plotfile=$proj-sen-MT$MT.zvd
 XWIN=`uname`
 if [ "$XWIN" = "Darwin" ] 
 then
-export DISPLAY=:0
+   if [ -z $DISPLAY ]; then export DISPLAY=:0 ; fi
 fi
 
 ln -sf $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit
 $EMPIREDIR/util/c4zvd/zvview.exe $plotfile ps01.tit/c
+    errCode=$?
+    #echo -n "___Pause. Press any key..."; read yes
+    #if [ $errCode -ne 0 ]; then
+    if [ $errCode -ne 0 -a $errCode -ne 1 ]; then
+        set +x
+        echo    "___ERROR running ZVView: errCode=$errCode"
+        echo    "___DISPLAY=$DISPLAY"
+        echo -n "___Pause. Press any key..."; read yes
+    fi
 rm ps01.tit
 exit
